name: Lint, Build and Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: [main, "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint, Build and Test packages
        run: |
          # Install shared dependencies
          npm install
          npm run bootstrap
          npm run lint
          npm run build
          npm run test
      - name: Upload test coverage
        run: |
          upload_coverage_script="${GITHUB_WORKSPACE}/scripts/uploadCoverage.sh"
          chmod +x $upload_coverage_script
          bash $upload_coverage_script
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
