name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          # Install vercel globally
          npm install vercel -g
          npm install
          npm run bootstrap
      - name: Deploy docs
        run: |
          cd ./docs
          npm install
          npm run build
          # Create the .vercel dir
          mkdir ./build/.vercel
          ls ./build
          # Create vercel project.json 
          echo {\"projectId\": $VERCEL_PROJECT_ID, \"orgId\": $VERCEL_ORG_ID} > ./build/.vercel/project.json
          npm run deploy --token $VERCEL_TOKEN
        env:
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
